steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'cr.yandex/crp3l3kun8448eciuhs4/oldbot26-image:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'cr.yandex/crp3l3kun8448eciuhs4/oldbot26-image:latest'
